services:
  web:
    build: .
    restart: always
    container_name: sca-web-app
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - sca_api_network

  db:
    image: postgres:17.0-alpine3.20
    restart: always
    container_name: sca-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - sca_api_network

networks:
  sca_api_network:
    driver: bridge

volumes:
  postgres_data: {}