# Generated by Django 5.1.3 on 2024-12-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="cats.cat",
            ),
        ),
    ]
